
# Either latest Debian release, or latest Ubuntu LTS release,
# which ever is newer.
FROM ubuntu:noble

MAINTAINER The Freeciv Project

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
          p7zip-full \
          meson \
          mingw-w64 \
          pkg-config \
          gettext \
          libtolua-dev \
          nsis \
          libdouble-conversion3 \
          libpcre2-16-0 \
    && DEBIAN_FRONTEND=noninteractive apt-get clean --yes

RUN mkdir /usr/crosser && mkdir /env

ARG CROSSER_PACKET

COPY input/${CROSSER_PACKET} /usr/crosser

RUN cd /usr/crosser && \
    7z x ${CROSSER_PACKET} && \
    rm ${CROSSER_PACKET}

COPY input/entry.sh input/freeciv_build.sh input/crosser-ver.sh /env/

ARG FREECIV_UID

# uid 1000 is already user "ubuntu"
RUN if test "${FREECIV_UID}" != "1000" ; then \
    adduser --gecos "" --uid ${FREECIV_UID} --disabled-password freeciv && \
    echo "freeciv" > /env/username.txt ; else echo "ubuntu" > /env/username.txt ; fi

WORKDIR /env

ENTRYPOINT ["/env/entry.sh", "-c", "--"]
